-- =============================================================================
-- SEED_TEST_DATA.sql: Optional test data for development/testing
--
-- IMPORTANT: This is NOT a migration. Run this ONLY if you want test data.
-- This script creates fake profiles with real UUIDs for testing.
-- 
-- Usage:
-- 1. Generate test user UUIDs first (or replace with real user IDs)
-- 2. Run this script in Supabase SQL Editor
-- =============================================================================

-- ─── DELETE OLD TEST POSTS (optional cleanup) ──────────────────────────────
-- Uncomment if re-running:
-- DELETE FROM post_likes WHERE post_id IN (
--   SELECT id FROM posts WHERE content LIKE '%NYC 최고%' OR content LIKE '%LA에서%'
-- );
-- DELETE FROM comments WHERE post_id IN (
--   SELECT id FROM posts WHERE content LIKE '%NYC 최고%' OR content LIKE '%LA에서%'
-- );
-- DELETE FROM posts WHERE content LIKE '%NYC 최고%' OR content LIKE '%LA에서%';

-- ─── Create test posts (no fake profile creation needed) ──────────────────────
-- Use your actual user ID (get from auth.users table):
-- SELECT id FROM auth.users LIMIT 1;

-- Example: Replace these UUIDs with real user IDs from your database
-- INSERT INTO posts (user_id, category, region_id, title, content, tags, created_at) VALUES
--   ('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'::UUID, 'general', 1, 
--    'NYC 최고의 카페 추천 해주세요!', 
--    '뉴욕에서 조용하고 좋은 카페 찾고있는데...',
--    ARRAY['뉴욕', '카페'], NOW());

-- ─── Instructions ──────────────────────────────────────────────────────────
-- To create test posts:
-- 1. Go to Supabase Dashboard → SQL Editor
-- 2. Run: SELECT id FROM auth.users LIMIT 5;
-- 3. Copy a user ID
-- 4. Replace 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' in INSERT statements
-- 5. Run the INSERT statements
-- 
-- Or test the API directly in your app:
-- 1. Login as your user
-- 2. Go to Community > 글쓰기
-- 3. Create a post (it will use your user_id automatically)
